site_name: STEM Robots
site_description: 'Resources for teaching computational thinking using low-cost robots. Content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/stem-robots'
repo_url: 'https://github.com/dmccreary/stem-robots'

nav:
  - Home: index.md
  - About This Website: about.md
  - Journey Map: journey-map.md
  - Robot Description: robot-description.md
  - Gallery: gallery/index.md
  - Great Ways To Teach: great-ways-to-teach.md
  - Course Descriptions:
    - Introductions: course-descriptions/index.md
    - Two Hour Hands On: course-descriptions/two-hour-hands-on.md
  - Getting Started:
    - setup/index.md
    - setup/05-thonny-installation.md
    - setup/10-base-kit-assembly.md
    - setup/20-parts-list.md
    - setup/30-tof-sensor.md
  - Personas: personas.md
  - Topics: topics.md
  - Lessons:
    - Introduction: lessons/index.md
    - Lesson Order: lessons/01-lesson-order.md
    - Robot Parts: lessons/03-robot-parts.md
    - Batteries: lessons/05-batteries.md
    - Config File: lessons/07-config-file.md
    - DC Motors: lessons/10-dc-motors.md
    - Motor Direction:  lessons/15-motor-direction.md
    - H-Bridge: lessons/16-h-bridge.md
    - Motor Speed: lessons/20-motor-speed.md
    - Pulse Width Modulation: lessons/25-pwm.md
    - Motor Connections: lessons/30-testing-motor-connections.md
    - Robot Dance: lessons/35-dance.md
    - I2C Bus: lessons/40-i2c-bus.md
    - Sensors: lessons/45-sensors.md
    - Time of Flight Sensor: lessons/50-tof-sensors.md
    - Ultrasonic Sensor: lessons/55-ultrasonic-sensors.md
    - Infrared Sensors: lessons/60-ir-sensors.md
    - Collision Avoidance: lessons/65-collision-avoidance.md
  - Base Bot:
    - Introduction: base/index.md
  - Sims:
    - Introduction: sims/index.md
    - H-Bridge: sims/h-bridge/index.md
    - Pulse Width Modulation: sims/pwm/index.md
    - Collision Avoidance: sims/collision-avoidance/index.md
  - Kits:
    - Introduction to Kits: kits/index.md
    - Base Robot:
      - Introduction: kits/base/index.md
      - kits/base/01-testing-motor-connections.md
      - kits/base/06-up-down-motor-lab.md
      - kits/base/07-motor-connection-lab.md
      - kits/base/07b-drive-square-lab.md
      - kits/base/08-servo-lab.md
      - kits/base/09-i2c-scanner-test.md
      - kits/base/10-time-of-flight-lab.md
      - kits/base/11-ping-lab.md
      - kits/base/12-time-of-flight-sound-lab.md
      - kits/base/20-collision-avoidance-robot.md
      - kits/base/21-collision-avoidance-ping.md
      - kits/base/23-microswitch-bot.md
      - kits/base/24-ping-servo-meter.md
      - kits/base/25-line-follower.md

    - Display Robot: kits/display/index.md
    - Bump Switches: kits/bump-switch/index.md
    - Line Follower: kits/line-follower/index.md
    - Adjustabot: kits/adjust/index.md
    - Ultrasonic: kits/ultrasonic/index.md
  - FAQ: faq.md
  - Glossary: glossary.md
  - References: references.md
  - License: license.md
  - Contact: contact.md

 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-6SSB9XBXM9